import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rozdział 4: Routing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="pl"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="bg-gray-800 text-white p-4">
          <ul className="flex space-x-4 max-w-4xl mx-auto">
            <li>
              <Link href="/" className="hover:text-blue-300 transition-colors">
                Strona główna
              </Link>
            </li>
            <li>
              <Link
                href="/users"
                className="hover:text-blue-300 transition-colors"
              >
                Katalog użytkowników
              </Link>
            </li>
          </ul>
        </nav>

        <main className="flex-1 p-4 max-w-4xl mx-auto w-full">{children}</main>
      </body>
    </html>
  );
}
